# Generated by Django 5.1.5 on 2025-01-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
