# Generated by Django 5.1.5 on 2025-02-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='media_type',
        ),
        migrations.AddField(
            model_name='productmedia',
            name='is_image',
            field=models.BooleanField(default=True),
        ),
    ]
