# Generated by Django 5.1.5 on 2025-02-01 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_productmedia_media_type_productmedia_is_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='is_image',
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='store.product'),
        ),
    ]
